language: node_js
node_js:
- '0.10'
before_install:
  - gem install sass
before_script:
  - npm install -g bower grunt-cli
  - bower install
after_success:
  - bash ./travis/deploy_heroku.sh
env:
  global:
    secure: "VYDtp46F1y7Rl4+J7v1L4K+ribZK5o01tdN74rgVlYvuMNSnyQ2YzeL6Dyy/v/oZCW8pV24BDxO12PslEwuU9N77vpDAJ5jl/ppOSusnqkfSFB3zQfDZXXdP7ncOUnJaJuxMIDDes7j2QNPSO4LEcBT3ecv9xw5/suwBBfNAMuo="
